"""SparkSage: structured, question-aligned knowledge chunks for RAG."""

from sparksage.api import (
    AddTagsRequest,
    AutoTagRequest,
    ConvertOutput,
    ConvertResponse,
    DocumentCreateResponse,
    DocumentListResponse,
    DocumentOut,
    DocumentUpdateRequest,
    GenerateOutput,
    GenerateResponse,
    GenerationNotConfiguredError,
    GenerationStatsOut,
    HealthResponse,
    ServiceError,
    SourceInfo,
    SparkSageService,
    TagCount,
    TagsResponse,
)
from sparksage.clean import (
    DEFAULT_RULES,
    CallableRule,
    CleaningRegistry,
    CleaningResult,
    CleaningRule,
    RegexReplaceRule,
    TextCleaner,
)
from sparksage.config import EnvParseError, load_dotenv, parse_env_file
from sparksage.convert import (
    DEFAULT_EXTENSIONS,
    ConversionResult,
    ConverterBackend,
    FakeConverterBackend,
    MarkdownConverter,
    MarkItDownBackend,
)
from sparksage.documents import (
    DEFAULT_AUTO_TAG_COUNT,
    DEFAULT_STOP_WORDS,
    Document,
    DocumentNotFoundError,
    DocumentService,
    DocumentServiceError,
    DocumentStore,
    FrequencyKeywordExtractor,
    InMemoryDocumentStore,
    KeywordExtractor,
)
from sparksage.generator import (
    FakeLLMClient,
    IdeaBlockGenerator,
    LLMClient,
    OpenAICompatibleClient,
)
from sparksage.schema.enums import (
    BlockStatus,
    EntityRelation,
    EntityType,
    SentenceRole,
    Tag,
    TagSource,
)
from sparksage.schema.ideablock import IdeaBlock
from sparksage.schema.technical import TechnicalBlock

__all__ = [
    "DEFAULT_AUTO_TAG_COUNT",
    "DEFAULT_EXTENSIONS",
    "DEFAULT_RULES",
    "DEFAULT_STOP_WORDS",
    "AddTagsRequest",
    "AutoTagRequest",
    "BlockStatus",
    "CallableRule",
    "CleaningRegistry",
    "CleaningResult",
    "CleaningRule",
    "ConvertOutput",
    "ConvertResponse",
    "ConversionResult",
    "ConverterBackend",
    "Document",
    "DocumentCreateResponse",
    "DocumentListResponse",
    "DocumentNotFoundError",
    "DocumentOut",
    "DocumentService",
    "DocumentServiceError",
    "DocumentStore",
    "DocumentUpdateRequest",
    "EntityRelation",
    "EntityType",
    "EnvParseError",
    "FakeConverterBackend",
    "FakeLLMClient",
    "FrequencyKeywordExtractor",
    "GenerateOutput",
    "GenerateResponse",
    "GenerationNotConfiguredError",
    "GenerationStatsOut",
    "HealthResponse",
    "IdeaBlock",
    "IdeaBlockGenerator",
    "InMemoryDocumentStore",
    "KeywordExtractor",
    "LLMClient",
    "MarkdownConverter",
    "MarkItDownBackend",
    "OpenAICompatibleClient",
    "RegexReplaceRule",
    "SentenceRole",
    "ServiceError",
    "SourceInfo",
    "SparkSageService",
    "Tag",
    "TagCount",
    "TagSource",
    "TagsResponse",
    "TechnicalBlock",
    "TextCleaner",
    "load_dotenv",
    "parse_env_file",
]

__version__ = "0.1.0"
